[package]
name = "address_book"
version = "0.1.0"
authors = ["mark"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
ncurses = "5.99"